# Generated by Django 3.1.5 on 2021-01-31 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('cnpj', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=255)),
                ('rua', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('tempo_preparo', models.CharField(blank=True, max_length=255)),
                ('disponivel', models.BooleanField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão'), ('picpay', 'Picpay'), ('pix', 'Pix'), ('transferencia', 'Trasferencia')], max_length=255)),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('obs', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('produtos', models.ManyToManyField(to='core.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='core.Produto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
