# Generated by Django 3.1.5 on 2021-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
