# Generated by Django 3.1.5 on 2021-01-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210118_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='form_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão'), ('picpay', 'Picpay'), ('pix', 'Pix'), ('transferencia', 'Trasferencia')], max_length=255),
        ),
    ]
